
package com.empresa.math.client.jax;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FibonacciServerService", targetNamespace = "http://server.math.empresa.com/", wsdlLocation = "http://192.168.30.178:9876/fib?wsdl")
@HandlerChain(file = "handler-chain.xml")
public class FibonacciServerService
    extends Service
{

    private final static URL FIBONACCISERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIBONACCISERVERSERVICE_EXCEPTION;
    private final static QName FIBONACCISERVERSERVICE_QNAME = new QName("http://server.math.empresa.com/", "FibonacciServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.30.178:9876/fib?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIBONACCISERVERSERVICE_WSDL_LOCATION = url;
        FIBONACCISERVERSERVICE_EXCEPTION = e;
    }

    public FibonacciServerService() {
        super(__getWsdlLocation(), FIBONACCISERVERSERVICE_QNAME);
    }

    public FibonacciServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIBONACCISERVERSERVICE_QNAME, features);
    }

    public FibonacciServerService(URL wsdlLocation) {
        super(wsdlLocation, FIBONACCISERVERSERVICE_QNAME);
    }

    public FibonacciServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIBONACCISERVERSERVICE_QNAME, features);
    }

    public FibonacciServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FibonacciServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FibonacciServer
     */
    @WebEndpoint(name = "FibonacciServerPort")
    public FibonacciServer getFibonacciServerPort() {
        return super.getPort(new QName("http://server.math.empresa.com/", "FibonacciServerPort"), FibonacciServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FibonacciServer
     */
    @WebEndpoint(name = "FibonacciServerPort")
    public FibonacciServer getFibonacciServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.math.empresa.com/", "FibonacciServerPort"), FibonacciServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIBONACCISERVERSERVICE_EXCEPTION!= null) {
            throw FIBONACCISERVERSERVICE_EXCEPTION;
        }
        return FIBONACCISERVERSERVICE_WSDL_LOCATION;
    }

}
